"""add game_data table

Revision ID: 78301114d396
Revises: 9ac50027ac88
Create Date: 2025-07-24 13:24:20.155522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78301114d396'
down_revision: Union[str, Sequence[str], None] = '9ac50027ac88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('row_type', sa.String(), nullable=True),
    sa.Column('inning', sa.String(), nullable=True),
    sa.Column('pitcher', sa.String(), nullable=True),
    sa.Column('batter', sa.String(), nullable=True),
    sa.Column('pitch_type', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('pitch_speed', sa.String(), nullable=True),
    sa.Column('exit_velocity', sa.String(), nullable=True),
    sa.Column('play_result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_data')
    # ### end Alembic commands ###
